### ISSUE TITLE
Production build failing: error from UglifyJs

### ISSUE THREAD

**Issue by dodas** [egoist/vuepack#30]
Hello,

when i build (`npm run build`) fresh vuepack, it compiles OK.
however, when i import some module, for example `jquery`, prod. build fails with error:

```
ERROR in vendor.795f4ce9.js from UglifyJs
SyntaxError: Unexpected token: name (cache) [vendor.795f4ce9.js:18852,4]
```

Is there some configuration I can change to supress this error?

thank you very much.

**Comment by egoist** [comment]
Can you provide more details on how you change the code, or a repo.

`npm i -S jquery` and `import $ from 'jquery'` just works for me.

**Comment by dodas** [comment]
Sorry, my bad, i had not fresh source.

What is creating this issue is module `googlemaps-js-rich-marker`. It is enough that this module is installed (don't have to be imported) for this issue to arise: `npm i -S googlemaps-js-rich-marker`

So now it is maybe not vuepack's failure. Could you guide me how to solve this? I am new to whole webpack/bundling/etc.

Thanks.

**Comment by egoist** [comment]
Ok, seems `googlemaps-js-rich-marker` needs to be compiled to es5

It failed because that package is written in ES6 and `uglifyjs` doesn't understand ES6 syntax, and we do not compile files in `node_modules` folder by default.

## Why it failed even if you didn't import `googlemaps-js-rich-marker`

Since vuepack splits all `dependencies` specified in `package.json` into a single `vendor.xxx.js`,  `googlemaps-js-rich-marker` will always be compiled by webpack and bundled into `vendor.xxx.js`

## How to fix

You should make `babel-loader` compile it to ES5. Checkout [webpack.base.js](https://github.com/egoist/vuepack/blob/master/template/build/webpack.base.js#L34-L36).

By default it excludes `node_modules` and does not handle `.es6` extension which [that module uses](https://github.com/slventures/googlemaps-js-rich-marker/tree/gh-pages/src), so the fix for you will be:

``` js
{
    test: /\.(js|es6)$/,
    loaders: ['babel'],
    // compile your app directory and some modules
    include: [/client/, /node_modules\/googlemaps-js-rich-marker/]
}
```

**Comment by dodas** [comment]
Thank you for detailed explanation, now I understand.
For the `loaders` part, wouldn't this be sufficient? Does it have any disadvantages?

```
{
  test: /\.js$/,
  loaders: ['babel'],
  exclude: [/node_modules/]
},
{
  test: /\.es6$/,
  loaders: ['babel']
}
```

**Comment by egoist** [comment]
Maybe yours is better. `.es6` should always be compiled to ES5

**Comment by dodas** [comment]
Great, don't you think this could be part od vuepack by default?

**Comment by egoist** [comment]
Updated 👏
