### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by peerbolte** [egoist/vuepack#97]
I get a `Uncaught ReferenceError: require is not defined` error in console when viewing `http://localhost:4000` after running `npm run dev`. The page stays blank.

ESLint - no
JSX - no
Electron - yes

Running `npm run app` simultaneously runs the app in Electron as expected though. I thought expected behaviour was to be able to run the web version by using `npm run dev` and the electron version using `npm run app`, or am I wrong?

node v7.4.0
vue-cli 2.8.0
osx

**Comment by egoist** [comment]
Check out https://github.com/egoist/vuepack/blob/master/docs/electron.md it does not work with browser directly.

**Comment by peerbolte** [comment]
Is the support for simultaneous web / electron development a possible feature for the future roadmap of vuepack? What kind of workflow would you suggest to do this with the current setup?

**Comment by egoist** [comment]
Since you may `require` electron-specified modules like `import {remote} from 'electron'`, current config (`target: 'electron-renderer'`) won't transform these built-in modules. so my answer is nope for now, suggestions are welcome.

For me, I will still separate web app and desktop app in two projects.

**Comment by khaledznobani** [comment]
@egoist 

I am running
```
npm run dev
```

If i run
```
npm run build
```

And open from the `/dist` it works but not with `npm run serve` then go to `localhost:4000`
